version: '1'
labels:
  - label: 'feature'
    title: 'Feature.*'
  - label: 'bug'
    title: 'Bug.*'
  - label: 'chore'
    title: 'Chore.*'
  - label: 'tooling'
    title: 'Tooling.*'
  - label: 'refactor'
    title: 'Refactor.*'
  - label: 'dependencies'
    title: 'Dependencies.*'
  - label: 'experiment'
    title: 'Experiment.*'
  - label: 'feature'
    branch: '^feature/.*'
  - label: 'bug'
    branch: '^bug/.*'
  - label: 'chore'
    branch: '^chore/.*'
  - label: 'tooling'
    branch: '^tooling/.*'
  - label: 'refactor'
    branch: '^refactor/.*'
  - label: 'dependencies'
    branch: '^dependencies/.*'
  - label: 'experiment'
    branch: '^experiment/.*'
