name: Label PRs
on:
  pull_request:
    branches: [development, main]
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
